name: app
description: "Smart Visual Imapred Glasses"
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  intl: ^0.19.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  toast: ^0.3.0
  # google_maps_flutter: ^2.2.0
  # uuid: ^4.0.0
  # go_router: ">=10.0.0 <14.0.0"
  # collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  # //analysis_defaults:
  #  // path: ../analysis_defaults
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true
  assets:
     - assets/images/dice-1.png
     - assets/images/dice-2.png
     - assets/images/dice-3.png
     - assets/images/dice-4.png